name: Production

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  install:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Build application
        run: npm run build --if-present
